spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: r1
              uri: http://localhost:8081
              predicates:
                - Path= /v1/equips/**
            - id: r2
              uri: http://localhost:8082
              predicates:
                - Path= /v1/joueurs/**

